name: Deploy to EC2

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload source to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "/home/ubuntu/JusinChatServerSrc"

    - name: Build & Restart server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
            pkill -f JusinChatServer || true
            cd ~/JusinChatServerSrc
            dotnet publish -c Release -r linux-x64 --self-contained true -p:PublishSingleFile=True -o output
            cd output
            chmod +x JusinChatServer
            nohup ./JusinChatServer > output.log 2>&1 &



